In [1]:
from sklearnex.model_selection import train_test_split
import pandas as pd

In [2]:
data = pd.read_csv('hypertension_data.csv')
data.drop(data[(data['trestbps'] > 120) & (data['target'] == 0)].index, inplace=True)
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,57.0,1.0,3,145,233,1,0,150,0,2.3,0,0,1,1
1,64.0,0.0,2,130,250,0,1,187,0,3.5,0,0,2,1
2,52.0,1.0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56.0,0.0,1,120,236,0,1,178,0,0.8,2,0,2,1
4,66.0,0.0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26063,70.0,0.0,2,120,178,1,1,96,0,0.0,2,0,2,1
26064,76.0,0.0,2,146,278,0,0,152,0,0.0,1,1,2,1
26065,57.0,1.0,2,130,253,0,1,179,0,0.0,2,0,2,1
26066,68.0,1.0,1,125,220,0,1,144,0,0.4,1,4,3,1
26080,68.0,1.0,0,100,234,0,1,156,0,0.1,2,1,3,0

In [3]:
X = data.drop('target', axis=1)
y = data['target']

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.1,random_state=42)

In [4]:
import pandas as pd

# Concatenate X_test and y_test horizontally
test_data = pd.concat([X_test, y_test], axis=1)

# Save the test data to a CSV file
test_data.to_csv('test_data.csv', index=False)

In [5]:
import pandas as pd

# Concatenate X_test and y_test horizontally
test_data = pd.concat([X_train, y_train], axis=1)

# Save the test data to a CSV file
test_data.to_csv('hypertension_data.csv', index=False)